site_name: Cancer Prediction
site_url: https://github.com/ph-u/packaging-publishing-pmh65
repo_url: https://github.com/ph-u/packaging-publishing-pmh65
nav:
  - Home: index.md
  - cancer-prediction:
      - cancer model: cancer_prediction/cancer_model.md
      - streamlit: cancer_prediction/streamlit_app.md
theme: readthedocs
plugins:
  - mkdocstrings
watch:
  - .